# Generated by Django 4.1.5 on 2023-02-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='city',
            name='temperature',
        ),
    ]
