# Generated by Django 4.1.5 on 2023-02-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_city_description_remove_city_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
    ]
