# Generated by Django 4.1.5 on 2023-02-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
    ]
